# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2d64dfbe7ca53fb841b91c1762c1aeb0e98c22881c50dbba354cff685678e9e1982d2bda435a90efc9d41e8ace093c2a129cc9ae27383105eb27d4edb808be2

test:
  secret_key_base: 607878d4e8c5ab3d231caefcbb0672a437c69e1ddf1605479fb4e191478c87e3e871898bede939b59526ffce91a01c83b2a6d57adae5be295cb25522d691b778

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
